//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// Nombre de archivo original:
// Fecha de generación: 09/02/2015 08:48:26 a.m.
namespace DCAddIn.DCDataServicio
{
    
    /// <summary>
    /// No hay comentarios para Entities en el esquema.
    /// </summary>
    public partial class Entities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Inicializar un nuevo objeto Entities.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Entities(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Como el espacio de nombres configurado para la referencia de este servicio
        /// en Visual Studio es diferente al indicado en el 
        /// esquema de servidor, use mapeadores de tipos para establecer asignaciones entre los dos.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "DCModelo", "DCAddIn.DCDataServicio");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Como el espacio de nombres configurado para la referencia de este servicio
        /// en Visual Studio es diferente al indicado en el 
        /// esquema de servidor, use mapeadores de tipos para establecer asignaciones entre los dos.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("DCAddIn.DCDataServicio", global::System.StringComparison.Ordinal))
            {
                return string.Concat("DCModelo.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// No hay comentarios para Tipoes en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Tipo> Tipoes
        {
            get
            {
                if ((this._Tipoes == null))
                {
                    this._Tipoes = base.CreateQuery<Tipo>("Tipoes");
                }
                return this._Tipoes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Tipo> _Tipoes;
        /// <summary>
        /// No hay comentarios para Procesoes en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Proceso> Procesoes
        {
            get
            {
                if ((this._Procesoes == null))
                {
                    this._Procesoes = base.CreateQuery<Proceso>("Procesoes");
                }
                return this._Procesoes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Proceso> _Procesoes;
        /// <summary>
        /// No hay comentarios para Cuentas en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Cuenta> Cuentas
        {
            get
            {
                if ((this._Cuentas == null))
                {
                    this._Cuentas = base.CreateQuery<Cuenta>("Cuentas");
                }
                return this._Cuentas;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Cuenta> _Cuentas;
        /// <summary>
        /// No hay comentarios para DocumentoFiles en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<DocumentoFile> DocumentoFiles
        {
            get
            {
                if ((this._DocumentoFiles == null))
                {
                    this._DocumentoFiles = base.CreateQuery<DocumentoFile>("DocumentoFiles");
                }
                return this._DocumentoFiles;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<DocumentoFile> _DocumentoFiles;
        /// <summary>
        /// No hay comentarios para FilePrincipals en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<FilePrincipal> FilePrincipals
        {
            get
            {
                if ((this._FilePrincipals == null))
                {
                    this._FilePrincipals = base.CreateQuery<FilePrincipal>("FilePrincipals");
                }
                return this._FilePrincipals;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<FilePrincipal> _FilePrincipals;
        /// <summary>
        /// No hay comentarios para Documentoes en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Documento> Documentoes
        {
            get
            {
                if ((this._Documentoes == null))
                {
                    this._Documentoes = base.CreateQuery<Documento>("Documentoes");
                }
                return this._Documentoes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Documento> _Documentoes;
        /// <summary>
        /// No hay comentarios para Tipoes en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTipoes(Tipo tipo)
        {
            base.AddObject("Tipoes", tipo);
        }
        /// <summary>
        /// No hay comentarios para Procesoes en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToProcesoes(Proceso proceso)
        {
            base.AddObject("Procesoes", proceso);
        }
        /// <summary>
        /// No hay comentarios para Cuentas en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCuentas(Cuenta cuenta)
        {
            base.AddObject("Cuentas", cuenta);
        }
        /// <summary>
        /// No hay comentarios para DocumentoFiles en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToDocumentoFiles(DocumentoFile documentoFile)
        {
            base.AddObject("DocumentoFiles", documentoFile);
        }
        /// <summary>
        /// No hay comentarios para FilePrincipals en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToFilePrincipals(FilePrincipal filePrincipal)
        {
            base.AddObject("FilePrincipals", filePrincipal);
        }
        /// <summary>
        /// No hay comentarios para Documentoes en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToDocumentoes(Documento documento)
        {
            base.AddObject("Documentoes", documento);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"DCModelo\" xmlns=\"http://schemas.microsoft.com/ado/2009/11/edm\"><Entit" +
                "yType Name=\"Tipo\"><Key><PropertyRef Name=\"TipoID\" /></Key><Property Name=\"TipoID" +
                "\" Type=\"Edm.Int16\" Nullable=\"false\" /><Property Name=\"Nombre\" Type=\"Edm.String\" " +
                "Nullable=\"false\" MaxLength=\"50\" FixedLength=\"false\" Unicode=\"false\" /><Navigatio" +
                "nProperty Name=\"Documentoes\" Relationship=\"DCModelo.fk_doc_doc_tipo\" ToRole=\"Doc" +
                "umento\" FromRole=\"Tipo\" /></EntityType><EntityType Name=\"Proceso\"><Key><Property" +
                "Ref Name=\"ProcesoID\" /></Key><Property Name=\"ProcesoID\" Type=\"Edm.Int16\" Nullabl" +
                "e=\"false\" /><Property Name=\"Nombre\" Type=\"Edm.String\" Nullable=\"false\" MaxLength" +
                "=\"50\" FixedLength=\"false\" Unicode=\"false\" /><NavigationProperty Name=\"Documentoe" +
                "s\" Relationship=\"DCModelo.fk_doc_doc_proceso\" ToRole=\"Documento\" FromRole=\"Proce" +
                "so\" /></EntityType><EntityType Name=\"Cuenta\"><Key><PropertyRef Name=\"CuentaID\" /" +
                "></Key><Property Name=\"CuentaID\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"3" +
                "0\" FixedLength=\"false\" Unicode=\"false\" /><Property Name=\"Nombre\" Type=\"Edm.Strin" +
                "g\" Nullable=\"false\" MaxLength=\"50\" FixedLength=\"false\" Unicode=\"false\" /><Proper" +
                "ty Name=\"Password\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"30\" FixedLength" +
                "=\"false\" Unicode=\"false\" /><Property Name=\"PasswordCorreo\" Type=\"Edm.String\" Nul" +
                "lable=\"false\" MaxLength=\"30\" FixedLength=\"false\" Unicode=\"false\" /><Property Nam" +
                "e=\"IndAdministrador\" Type=\"Edm.Int16\" Nullable=\"false\" /><NavigationProperty Nam" +
                "e=\"Documentoes\" Relationship=\"DCModelo.fk_doc_doc_cuenta\" ToRole=\"Documento\" Fro" +
                "mRole=\"Cuenta\" /></EntityType><EntityType Name=\"DocumentoFile\"><Key><PropertyRef" +
                " Name=\"Ano\" /><PropertyRef Name=\"Archivo\" /><PropertyRef Name=\"Carpeta\" /><Prope" +
                "rtyRef Name=\"CodigoCliente\" /><PropertyRef Name=\"CuentaID\" /><PropertyRef Name=\"" +
                "DocumentoID\" /><PropertyRef Name=\"FechaHora\" /><PropertyRef Name=\"FechaHoraProce" +
                "so\" /><PropertyRef Name=\"Identificador\" /><PropertyRef Name=\"Nombre\" /><Property" +
                "Ref Name=\"NumFile\" /><PropertyRef Name=\"NumFileFisico\" /><PropertyRef Name=\"Proc" +
                "esoID\" /><PropertyRef Name=\"TipoID\" /></Key><Property Name=\"DocumentoID\" Type=\"E" +
                "dm.Int64\" Nullable=\"false\" /><Property Name=\"Ano\" Type=\"Edm.String\" Nullable=\"fa" +
                "lse\" MaxLength=\"4\" FixedLength=\"false\" Unicode=\"false\" /><Property Name=\"NumFile" +
                "\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"10\" FixedLength=\"false\" Unicode=" +
                "\"false\" /><Property Name=\"NumFileFisico\" Type=\"Edm.String\" Nullable=\"false\" MaxL" +
                "ength=\"5\" FixedLength=\"false\" Unicode=\"false\" /><Property Name=\"ProcesoID\" Type=" +
                "\"Edm.Int16\" Nullable=\"false\" /><Property Name=\"TipoID\" Type=\"Edm.Int16\" Nullable" +
                "=\"false\" /><Property Name=\"Nombre\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=" +
                "\"500\" FixedLength=\"false\" Unicode=\"false\" /><Property Name=\"Nota\" Type=\"Edm.Stri" +
                "ng\" MaxLength=\"500\" FixedLength=\"false\" Unicode=\"false\" /><Property Name=\"Cuenta" +
                "ID\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"30\" FixedLength=\"false\" Unicod" +
                "e=\"false\" /><Property Name=\"Carpeta\" Type=\"Edm.String\" Nullable=\"false\" MaxLengt" +
                "h=\"255\" FixedLength=\"false\" Unicode=\"false\" /><Property Name=\"Identificador\" Typ" +
                "e=\"Edm.String\" Nullable=\"false\" MaxLength=\"100\" FixedLength=\"false\" Unicode=\"fal" +
                "se\" /><Property Name=\"Archivo\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"255" +
                "\" FixedLength=\"false\" Unicode=\"false\" /><Property Name=\"Sender\" Type=\"Edm.String" +
                "\" MaxLength=\"100\" FixedLength=\"false\" Unicode=\"false\" /><Property Name=\"Reciever" +
                "\" Type=\"Edm.String\" MaxLength=\"500\" FixedLength=\"false\" Unicode=\"false\" /><Prope" +
                "rty Name=\"FechaHora\" Type=\"Edm.DateTime\" Nullable=\"false\" /><Property Name=\"Fech" +
                "aHoraProceso\" Type=\"Edm.DateTime\" Nullable=\"false\" /><Property Name=\"NombreFile\"" +
                " Type=\"Edm.String\" MaxLength=\"50\" FixedLength=\"false\" Unicode=\"false\" /><Propert" +
                "y Name=\"Mercado\" Type=\"Edm.String\" MaxLength=\"50\" FixedLength=\"false\" Unicode=\"f" +
                "alse\" /><Property Name=\"NombreCliente\" Type=\"Edm.String\" MaxLength=\"50\" FixedLen" +
                "gth=\"false\" Unicode=\"false\" /><Property Name=\"CodigoCliente\" Type=\"Edm.String\" N" +
                "ullable=\"false\" MaxLength=\"10\" FixedLength=\"false\" Unicode=\"false\" /><Property N" +
                "ame=\"AnoFile\" Type=\"Edm.String\" MaxLength=\"43\" FixedLength=\"false\" Unicode=\"fals" +
                "e\" /></EntityType><EntityType Name=\"FilePrincipal\"><Key><PropertyRef Name=\"Ano\" " +
                "/><PropertyRef Name=\"NumFile\" /><PropertyRef Name=\"TipTarifario\" /></Key><Proper" +
                "ty Name=\"Ano\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"4\" FixedLength=\"fals" +
                "e\" Unicode=\"false\" /><Property Name=\"NumFile\" Type=\"Edm.String\" Nullable=\"false\"" +
                " MaxLength=\"10\" FixedLength=\"false\" Unicode=\"false\" /><Property Name=\"TipTarifar" +
                "io\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"2\" FixedLength=\"false\" Unicode" +
                "=\"false\" /><Property Name=\"NumFileFisico\" Type=\"Edm.String\" MaxLength=\"5\" FixedL" +
                "ength=\"false\" Unicode=\"false\" /><Property Name=\"AnoFile\" Type=\"Edm.String\" MaxLe" +
                "ngth=\"10\" FixedLength=\"false\" Unicode=\"false\" /><Property Name=\"Nombre\" Type=\"Ed" +
                "m.String\" MaxLength=\"50\" FixedLength=\"false\" Unicode=\"false\" /><Property Name=\"M" +
                "ercado\" Type=\"Edm.String\" MaxLength=\"50\" FixedLength=\"false\" Unicode=\"false\" /><" +
                "/EntityType><EntityType Name=\"Documento\"><Key><PropertyRef Name=\"DocumentoID\" />" +
                "</Key><Property Name=\"DocumentoID\" Type=\"Edm.Int64\" Nullable=\"false\" /><Property" +
                " Name=\"Ano\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"4\" FixedLength=\"false\"" +
                " Unicode=\"false\" /><Property Name=\"NumFile\" Type=\"Edm.String\" Nullable=\"false\" M" +
                "axLength=\"10\" FixedLength=\"false\" Unicode=\"false\" /><Property Name=\"NumFileFisic" +
                "o\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"5\" FixedLength=\"false\" Unicode=" +
                "\"false\" /><Property Name=\"ProcesoID\" Type=\"Edm.Int16\" Nullable=\"false\" /><Proper" +
                "ty Name=\"TipoID\" Type=\"Edm.Int16\" Nullable=\"false\" /><Property Name=\"Nombre\" Typ" +
                "e=\"Edm.String\" Nullable=\"false\" MaxLength=\"500\" FixedLength=\"false\" Unicode=\"fal" +
                "se\" /><Property Name=\"Nota\" Type=\"Edm.String\" MaxLength=\"500\" FixedLength=\"false" +
                "\" Unicode=\"false\" /><Property Name=\"CuentaID\" Type=\"Edm.String\" Nullable=\"false\"" +
                " MaxLength=\"30\" FixedLength=\"false\" Unicode=\"false\" /><Property Name=\"Carpeta\" T" +
                "ype=\"Edm.String\" Nullable=\"false\" MaxLength=\"255\" FixedLength=\"false\" Unicode=\"f" +
                "alse\" /><Property Name=\"Identificador\" Type=\"Edm.String\" Nullable=\"false\" MaxLen" +
                "gth=\"100\" FixedLength=\"false\" Unicode=\"false\" /><Property Name=\"Archivo\" Type=\"E" +
                "dm.String\" Nullable=\"false\" MaxLength=\"255\" FixedLength=\"false\" Unicode=\"false\" " +
                "/><Property Name=\"Sender\" Type=\"Edm.String\" MaxLength=\"100\" FixedLength=\"false\" " +
                "Unicode=\"false\" /><Property Name=\"Reciever\" Type=\"Edm.String\" MaxLength=\"500\" Fi" +
                "xedLength=\"false\" Unicode=\"false\" /><Property Name=\"FechaHora\" Type=\"Edm.DateTim" +
                "e\" Nullable=\"false\" /><Property Name=\"FechaHoraProceso\" Type=\"Edm.DateTime\" Null" +
                "able=\"false\" /><NavigationProperty Name=\"Cuenta\" Relationship=\"DCModelo.fk_doc_d" +
                "oc_cuenta\" ToRole=\"Cuenta\" FromRole=\"Documento\" /><NavigationProperty Name=\"Proc" +
                "eso\" Relationship=\"DCModelo.fk_doc_doc_proceso\" ToRole=\"Proceso\" FromRole=\"Docum" +
                "ento\" /><NavigationProperty Name=\"Tipo\" Relationship=\"DCModelo.fk_doc_doc_tipo\" " +
                "ToRole=\"Tipo\" FromRole=\"Documento\" /></EntityType><Association Name=\"fk_doc_doc_" +
                "tipo\"><End Type=\"DCModelo.Tipo\" Role=\"Tipo\" Multiplicity=\"1\" /><End Type=\"DCMode" +
                "lo.Documento\" Role=\"Documento\" Multiplicity=\"*\" /><ReferentialConstraint><Princi" +
                "pal Role=\"Tipo\"><PropertyRef Name=\"TipoID\" /></Principal><Dependent Role=\"Docume" +
                "nto\"><PropertyRef Name=\"TipoID\" /></Dependent></Referential";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart1 = "Constraint></Association><Association Name=\"fk_doc_doc_proceso\"><End Type=\"DCMode" +
                "lo.Proceso\" Role=\"Proceso\" Multiplicity=\"1\" /><End Type=\"DCModelo.Documento\" Rol" +
                "e=\"Documento\" Multiplicity=\"*\" /><ReferentialConstraint><Principal Role=\"Proceso" +
                "\"><PropertyRef Name=\"ProcesoID\" /></Principal><Dependent Role=\"Documento\"><Prope" +
                "rtyRef Name=\"ProcesoID\" /></Dependent></ReferentialConstraint></Association><Ass" +
                "ociation Name=\"fk_doc_doc_cuenta\"><End Type=\"DCModelo.Cuenta\" Role=\"Cuenta\" Mult" +
                "iplicity=\"1\" /><End Type=\"DCModelo.Documento\" Role=\"Documento\" Multiplicity=\"*\" " +
                "/><ReferentialConstraint><Principal Role=\"Cuenta\"><PropertyRef Name=\"CuentaID\" /" +
                "></Principal><Dependent Role=\"Documento\"><PropertyRef Name=\"CuentaID\" /></Depend" +
                "ent></ReferentialConstraint></Association><EntityContainer Name=\"Entities\" m:IsD" +
                "efaultEntityContainer=\"true\" p6:LazyLoadingEnabled=\"true\" xmlns:p6=\"http://schem" +
                "as.microsoft.com/ado/2009/02/edm/annotation\"><EntitySet Name=\"Tipoes\" EntityType" +
                "=\"DCModelo.Tipo\" /><EntitySet Name=\"Procesoes\" EntityType=\"DCModelo.Proceso\" /><" +
                "EntitySet Name=\"Cuentas\" EntityType=\"DCModelo.Cuenta\" /><EntitySet Name=\"Documen" +
                "toFiles\" EntityType=\"DCModelo.DocumentoFile\" /><EntitySet Name=\"FilePrincipals\" " +
                "EntityType=\"DCModelo.FilePrincipal\" /><EntitySet Name=\"Documentoes\" EntityType=\"" +
                "DCModelo.Documento\" /><AssociationSet Name=\"fk_doc_doc_tipo\" Association=\"DCMode" +
                "lo.fk_doc_doc_tipo\"><End Role=\"Tipo\" EntitySet=\"Tipoes\" /><End Role=\"Documento\" " +
                "EntitySet=\"Documentoes\" /></AssociationSet><AssociationSet Name=\"fk_doc_doc_proc" +
                "eso\" Association=\"DCModelo.fk_doc_doc_proceso\"><End Role=\"Proceso\" EntitySet=\"Pr" +
                "ocesoes\" /><End Role=\"Documento\" EntitySet=\"Documentoes\" /></AssociationSet><Ass" +
                "ociationSet Name=\"fk_doc_doc_cuenta\" Association=\"DCModelo.fk_doc_doc_cuenta\"><E" +
                "nd Role=\"Cuenta\" EntitySet=\"Cuentas\" /><End Role=\"Documento\" EntitySet=\"Document" +
                "oes\" /></AssociationSet></EntityContainer></Schema></edmx:DataServices></edmx:Ed" +
                "mx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0, ModelPart1);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// No hay comentarios para DCModelo.Tipo en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// TipoID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Tipoes")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("TipoID")]
    public partial class Tipo : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Crear un nuevo objeto Tipo.
        /// </summary>
        /// <param name="tipoID">Valor inicial de TipoID.</param>
        /// <param name="nombre">Valor inicial de Nombre.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Tipo CreateTipo(short tipoID, string nombre)
        {
            Tipo tipo = new Tipo();
            tipo.TipoID = tipoID;
            tipo.Nombre = nombre;
            return tipo;
        }
        /// <summary>
        /// No hay comentarios para la propiedad TipoID en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public short TipoID
        {
            get
            {
                return this._TipoID;
            }
            set
            {
                this.OnTipoIDChanging(value);
                this._TipoID = value;
                this.OnTipoIDChanged();
                this.OnPropertyChanged("TipoID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private short _TipoID;
        partial void OnTipoIDChanging(short value);
        partial void OnTipoIDChanged();
        /// <summary>
        /// No hay comentarios para la propiedad Nombre en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Nombre
        {
            get
            {
                return this._Nombre;
            }
            set
            {
                this.OnNombreChanging(value);
                this._Nombre = value;
                this.OnNombreChanged();
                this.OnPropertyChanged("Nombre");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Nombre;
        partial void OnNombreChanging(string value);
        partial void OnNombreChanged();
        /// <summary>
        /// No hay comentarios para Documentoes en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Documento> Documentoes
        {
            get
            {
                return this._Documentoes;
            }
            set
            {
                this._Documentoes = value;
                this.OnPropertyChanged("Documentoes");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Documento> _Documentoes = new global::System.Data.Services.Client.DataServiceCollection<Documento>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// No hay comentarios para DCModelo.Proceso en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// ProcesoID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Procesoes")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ProcesoID")]
    public partial class Proceso : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Crear un nuevo objeto Proceso.
        /// </summary>
        /// <param name="procesoID">Valor inicial de ProcesoID.</param>
        /// <param name="nombre">Valor inicial de Nombre.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Proceso CreateProceso(short procesoID, string nombre)
        {
            Proceso proceso = new Proceso();
            proceso.ProcesoID = procesoID;
            proceso.Nombre = nombre;
            return proceso;
        }
        /// <summary>
        /// No hay comentarios para la propiedad ProcesoID en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public short ProcesoID
        {
            get
            {
                return this._ProcesoID;
            }
            set
            {
                this.OnProcesoIDChanging(value);
                this._ProcesoID = value;
                this.OnProcesoIDChanged();
                this.OnPropertyChanged("ProcesoID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private short _ProcesoID;
        partial void OnProcesoIDChanging(short value);
        partial void OnProcesoIDChanged();
        /// <summary>
        /// No hay comentarios para la propiedad Nombre en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Nombre
        {
            get
            {
                return this._Nombre;
            }
            set
            {
                this.OnNombreChanging(value);
                this._Nombre = value;
                this.OnNombreChanged();
                this.OnPropertyChanged("Nombre");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Nombre;
        partial void OnNombreChanging(string value);
        partial void OnNombreChanged();
        /// <summary>
        /// No hay comentarios para Documentoes en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Documento> Documentoes
        {
            get
            {
                return this._Documentoes;
            }
            set
            {
                this._Documentoes = value;
                this.OnPropertyChanged("Documentoes");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Documento> _Documentoes = new global::System.Data.Services.Client.DataServiceCollection<Documento>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// No hay comentarios para DCModelo.Cuenta en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// CuentaID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Cuentas")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("CuentaID")]
    public partial class Cuenta : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Crear un nuevo objeto Cuenta.
        /// </summary>
        /// <param name="cuentaID">Valor inicial de CuentaID.</param>
        /// <param name="nombre">Valor inicial de Nombre.</param>
        /// <param name="password">Valor inicial de Password.</param>
        /// <param name="passwordCorreo">Valor inicial de PasswordCorreo.</param>
        /// <param name="indAdministrador">Valor inicial de IndAdministrador.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Cuenta CreateCuenta(string cuentaID, string nombre, string password, string passwordCorreo, short indAdministrador)
        {
            Cuenta cuenta = new Cuenta();
            cuenta.CuentaID = cuentaID;
            cuenta.Nombre = nombre;
            cuenta.Password = password;
            cuenta.PasswordCorreo = passwordCorreo;
            cuenta.IndAdministrador = indAdministrador;
            return cuenta;
        }
        /// <summary>
        /// No hay comentarios para la propiedad CuentaID en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CuentaID
        {
            get
            {
                return this._CuentaID;
            }
            set
            {
                this.OnCuentaIDChanging(value);
                this._CuentaID = value;
                this.OnCuentaIDChanged();
                this.OnPropertyChanged("CuentaID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CuentaID;
        partial void OnCuentaIDChanging(string value);
        partial void OnCuentaIDChanged();
        /// <summary>
        /// No hay comentarios para la propiedad Nombre en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Nombre
        {
            get
            {
                return this._Nombre;
            }
            set
            {
                this.OnNombreChanging(value);
                this._Nombre = value;
                this.OnNombreChanged();
                this.OnPropertyChanged("Nombre");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Nombre;
        partial void OnNombreChanging(string value);
        partial void OnNombreChanged();
        /// <summary>
        /// No hay comentarios para la propiedad Password en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Password
        {
            get
            {
                return this._Password;
            }
            set
            {
                this.OnPasswordChanging(value);
                this._Password = value;
                this.OnPasswordChanged();
                this.OnPropertyChanged("Password");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Password;
        partial void OnPasswordChanging(string value);
        partial void OnPasswordChanged();
        /// <summary>
        /// No hay comentarios para la propiedad PasswordCorreo en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PasswordCorreo
        {
            get
            {
                return this._PasswordCorreo;
            }
            set
            {
                this.OnPasswordCorreoChanging(value);
                this._PasswordCorreo = value;
                this.OnPasswordCorreoChanged();
                this.OnPropertyChanged("PasswordCorreo");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PasswordCorreo;
        partial void OnPasswordCorreoChanging(string value);
        partial void OnPasswordCorreoChanged();
        /// <summary>
        /// No hay comentarios para la propiedad IndAdministrador en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public short IndAdministrador
        {
            get
            {
                return this._IndAdministrador;
            }
            set
            {
                this.OnIndAdministradorChanging(value);
                this._IndAdministrador = value;
                this.OnIndAdministradorChanged();
                this.OnPropertyChanged("IndAdministrador");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private short _IndAdministrador;
        partial void OnIndAdministradorChanging(short value);
        partial void OnIndAdministradorChanged();
        /// <summary>
        /// No hay comentarios para Documentoes en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Documento> Documentoes
        {
            get
            {
                return this._Documentoes;
            }
            set
            {
                this._Documentoes = value;
                this.OnPropertyChanged("Documentoes");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Documento> _Documentoes = new global::System.Data.Services.Client.DataServiceCollection<Documento>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// No hay comentarios para DCModelo.DocumentoFile en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// Ano
    /// Archivo
    /// Carpeta
    /// CodigoCliente
    /// CuentaID
    /// DocumentoID
    /// FechaHora
    /// FechaHoraProceso
    /// Identificador
    /// Nombre
    /// NumFile
    /// NumFileFisico
    /// ProcesoID
    /// TipoID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("DocumentoFiles")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Ano", "Archivo", "Carpeta", "CodigoCliente", "CuentaID", "DocumentoID", "FechaHora", "FechaHoraProceso", "Identificador", "Nombre", "NumFile", "NumFileFisico", "ProcesoID", "TipoID")]
    public partial class DocumentoFile : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Crear un nuevo objeto DocumentoFile.
        /// </summary>
        /// <param name="documentoID">Valor inicial de DocumentoID.</param>
        /// <param name="ano">Valor inicial de Ano.</param>
        /// <param name="numFile">Valor inicial de NumFile.</param>
        /// <param name="numFileFisico">Valor inicial de NumFileFisico.</param>
        /// <param name="procesoID">Valor inicial de ProcesoID.</param>
        /// <param name="tipoID">Valor inicial de TipoID.</param>
        /// <param name="nombre">Valor inicial de Nombre.</param>
        /// <param name="cuentaID">Valor inicial de CuentaID.</param>
        /// <param name="carpeta">Valor inicial de Carpeta.</param>
        /// <param name="identificador">Valor inicial de Identificador.</param>
        /// <param name="archivo">Valor inicial de Archivo.</param>
        /// <param name="fechaHora">Valor inicial de FechaHora.</param>
        /// <param name="fechaHoraProceso">Valor inicial de FechaHoraProceso.</param>
        /// <param name="codigoCliente">Valor inicial de CodigoCliente.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static DocumentoFile CreateDocumentoFile(long documentoID, string ano, string numFile, string numFileFisico, short procesoID, short tipoID, string nombre, string cuentaID, string carpeta, string identificador, string archivo, global::System.DateTime fechaHora, global::System.DateTime fechaHoraProceso, string codigoCliente)
        {
            DocumentoFile documentoFile = new DocumentoFile();
            documentoFile.DocumentoID = documentoID;
            documentoFile.Ano = ano;
            documentoFile.NumFile = numFile;
            documentoFile.NumFileFisico = numFileFisico;
            documentoFile.ProcesoID = procesoID;
            documentoFile.TipoID = tipoID;
            documentoFile.Nombre = nombre;
            documentoFile.CuentaID = cuentaID;
            documentoFile.Carpeta = carpeta;
            documentoFile.Identificador = identificador;
            documentoFile.Archivo = archivo;
            documentoFile.FechaHora = fechaHora;
            documentoFile.FechaHoraProceso = fechaHoraProceso;
            documentoFile.CodigoCliente = codigoCliente;
            return documentoFile;
        }
        /// <summary>
        /// No hay comentarios para la propiedad DocumentoID en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long DocumentoID
        {
            get
            {
                return this._DocumentoID;
            }
            set
            {
                this.OnDocumentoIDChanging(value);
                this._DocumentoID = value;
                this.OnDocumentoIDChanged();
                this.OnPropertyChanged("DocumentoID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _DocumentoID;
        partial void OnDocumentoIDChanging(long value);
        partial void OnDocumentoIDChanged();
        /// <summary>
        /// No hay comentarios para la propiedad Ano en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Ano
        {
            get
            {
                return this._Ano;
            }
            set
            {
                this.OnAnoChanging(value);
                this._Ano = value;
                this.OnAnoChanged();
                this.OnPropertyChanged("Ano");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Ano;
        partial void OnAnoChanging(string value);
        partial void OnAnoChanged();
        /// <summary>
        /// No hay comentarios para la propiedad NumFile en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string NumFile
        {
            get
            {
                return this._NumFile;
            }
            set
            {
                this.OnNumFileChanging(value);
                this._NumFile = value;
                this.OnNumFileChanged();
                this.OnPropertyChanged("NumFile");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _NumFile;
        partial void OnNumFileChanging(string value);
        partial void OnNumFileChanged();
        /// <summary>
        /// No hay comentarios para la propiedad NumFileFisico en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string NumFileFisico
        {
            get
            {
                return this._NumFileFisico;
            }
            set
            {
                this.OnNumFileFisicoChanging(value);
                this._NumFileFisico = value;
                this.OnNumFileFisicoChanged();
                this.OnPropertyChanged("NumFileFisico");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _NumFileFisico;
        partial void OnNumFileFisicoChanging(string value);
        partial void OnNumFileFisicoChanged();
        /// <summary>
        /// No hay comentarios para la propiedad ProcesoID en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public short ProcesoID
        {
            get
            {
                return this._ProcesoID;
            }
            set
            {
                this.OnProcesoIDChanging(value);
                this._ProcesoID = value;
                this.OnProcesoIDChanged();
                this.OnPropertyChanged("ProcesoID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private short _ProcesoID;
        partial void OnProcesoIDChanging(short value);
        partial void OnProcesoIDChanged();
        /// <summary>
        /// No hay comentarios para la propiedad TipoID en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public short TipoID
        {
            get
            {
                return this._TipoID;
            }
            set
            {
                this.OnTipoIDChanging(value);
                this._TipoID = value;
                this.OnTipoIDChanged();
                this.OnPropertyChanged("TipoID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private short _TipoID;
        partial void OnTipoIDChanging(short value);
        partial void OnTipoIDChanged();
        /// <summary>
        /// No hay comentarios para la propiedad Nombre en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Nombre
        {
            get
            {
                return this._Nombre;
            }
            set
            {
                this.OnNombreChanging(value);
                this._Nombre = value;
                this.OnNombreChanged();
                this.OnPropertyChanged("Nombre");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Nombre;
        partial void OnNombreChanging(string value);
        partial void OnNombreChanged();
        /// <summary>
        /// No hay comentarios para la propiedad Nota en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Nota
        {
            get
            {
                return this._Nota;
            }
            set
            {
                this.OnNotaChanging(value);
                this._Nota = value;
                this.OnNotaChanged();
                this.OnPropertyChanged("Nota");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Nota;
        partial void OnNotaChanging(string value);
        partial void OnNotaChanged();
        /// <summary>
        /// No hay comentarios para la propiedad CuentaID en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CuentaID
        {
            get
            {
                return this._CuentaID;
            }
            set
            {
                this.OnCuentaIDChanging(value);
                this._CuentaID = value;
                this.OnCuentaIDChanged();
                this.OnPropertyChanged("CuentaID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CuentaID;
        partial void OnCuentaIDChanging(string value);
        partial void OnCuentaIDChanged();
        /// <summary>
        /// No hay comentarios para la propiedad Carpeta en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Carpeta
        {
            get
            {
                return this._Carpeta;
            }
            set
            {
                this.OnCarpetaChanging(value);
                this._Carpeta = value;
                this.OnCarpetaChanged();
                this.OnPropertyChanged("Carpeta");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Carpeta;
        partial void OnCarpetaChanging(string value);
        partial void OnCarpetaChanged();
        /// <summary>
        /// No hay comentarios para la propiedad Identificador en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Identificador
        {
            get
            {
                return this._Identificador;
            }
            set
            {
                this.OnIdentificadorChanging(value);
                this._Identificador = value;
                this.OnIdentificadorChanged();
                this.OnPropertyChanged("Identificador");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Identificador;
        partial void OnIdentificadorChanging(string value);
        partial void OnIdentificadorChanged();
        /// <summary>
        /// No hay comentarios para la propiedad Archivo en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Archivo
        {
            get
            {
                return this._Archivo;
            }
            set
            {
                this.OnArchivoChanging(value);
                this._Archivo = value;
                this.OnArchivoChanged();
                this.OnPropertyChanged("Archivo");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Archivo;
        partial void OnArchivoChanging(string value);
        partial void OnArchivoChanged();
        /// <summary>
        /// No hay comentarios para la propiedad Sender en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Sender
        {
            get
            {
                return this._Sender;
            }
            set
            {
                this.OnSenderChanging(value);
                this._Sender = value;
                this.OnSenderChanged();
                this.OnPropertyChanged("Sender");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Sender;
        partial void OnSenderChanging(string value);
        partial void OnSenderChanged();
        /// <summary>
        /// No hay comentarios para la propiedad Reciever en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Reciever
        {
            get
            {
                return this._Reciever;
            }
            set
            {
                this.OnRecieverChanging(value);
                this._Reciever = value;
                this.OnRecieverChanged();
                this.OnPropertyChanged("Reciever");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Reciever;
        partial void OnRecieverChanging(string value);
        partial void OnRecieverChanged();
        /// <summary>
        /// No hay comentarios para la propiedad FechaHora en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime FechaHora
        {
            get
            {
                return this._FechaHora;
            }
            set
            {
                this.OnFechaHoraChanging(value);
                this._FechaHora = value;
                this.OnFechaHoraChanged();
                this.OnPropertyChanged("FechaHora");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _FechaHora;
        partial void OnFechaHoraChanging(global::System.DateTime value);
        partial void OnFechaHoraChanged();
        /// <summary>
        /// No hay comentarios para la propiedad FechaHoraProceso en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime FechaHoraProceso
        {
            get
            {
                return this._FechaHoraProceso;
            }
            set
            {
                this.OnFechaHoraProcesoChanging(value);
                this._FechaHoraProceso = value;
                this.OnFechaHoraProcesoChanged();
                this.OnPropertyChanged("FechaHoraProceso");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _FechaHoraProceso;
        partial void OnFechaHoraProcesoChanging(global::System.DateTime value);
        partial void OnFechaHoraProcesoChanged();
        /// <summary>
        /// No hay comentarios para la propiedad NombreFile en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string NombreFile
        {
            get
            {
                return this._NombreFile;
            }
            set
            {
                this.OnNombreFileChanging(value);
                this._NombreFile = value;
                this.OnNombreFileChanged();
                this.OnPropertyChanged("NombreFile");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _NombreFile;
        partial void OnNombreFileChanging(string value);
        partial void OnNombreFileChanged();
        /// <summary>
        /// No hay comentarios para la propiedad Mercado en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Mercado
        {
            get
            {
                return this._Mercado;
            }
            set
            {
                this.OnMercadoChanging(value);
                this._Mercado = value;
                this.OnMercadoChanged();
                this.OnPropertyChanged("Mercado");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Mercado;
        partial void OnMercadoChanging(string value);
        partial void OnMercadoChanged();
        /// <summary>
        /// No hay comentarios para la propiedad NombreCliente en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string NombreCliente
        {
            get
            {
                return this._NombreCliente;
            }
            set
            {
                this.OnNombreClienteChanging(value);
                this._NombreCliente = value;
                this.OnNombreClienteChanged();
                this.OnPropertyChanged("NombreCliente");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _NombreCliente;
        partial void OnNombreClienteChanging(string value);
        partial void OnNombreClienteChanged();
        /// <summary>
        /// No hay comentarios para la propiedad CodigoCliente en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CodigoCliente
        {
            get
            {
                return this._CodigoCliente;
            }
            set
            {
                this.OnCodigoClienteChanging(value);
                this._CodigoCliente = value;
                this.OnCodigoClienteChanged();
                this.OnPropertyChanged("CodigoCliente");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CodigoCliente;
        partial void OnCodigoClienteChanging(string value);
        partial void OnCodigoClienteChanged();
        /// <summary>
        /// No hay comentarios para la propiedad AnoFile en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AnoFile
        {
            get
            {
                return this._AnoFile;
            }
            set
            {
                this.OnAnoFileChanging(value);
                this._AnoFile = value;
                this.OnAnoFileChanged();
                this.OnPropertyChanged("AnoFile");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AnoFile;
        partial void OnAnoFileChanging(string value);
        partial void OnAnoFileChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// No hay comentarios para DCModelo.FilePrincipal en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// Ano
    /// NumFile
    /// TipTarifario
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("FilePrincipals")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Ano", "NumFile", "TipTarifario")]
    public partial class FilePrincipal : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Crear un nuevo objeto FilePrincipal.
        /// </summary>
        /// <param name="ano">Valor inicial de Ano.</param>
        /// <param name="numFile">Valor inicial de NumFile.</param>
        /// <param name="tipTarifario">Valor inicial de TipTarifario.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static FilePrincipal CreateFilePrincipal(string ano, string numFile, string tipTarifario)
        {
            FilePrincipal filePrincipal = new FilePrincipal();
            filePrincipal.Ano = ano;
            filePrincipal.NumFile = numFile;
            filePrincipal.TipTarifario = tipTarifario;
            return filePrincipal;
        }
        /// <summary>
        /// No hay comentarios para la propiedad Ano en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Ano
        {
            get
            {
                return this._Ano;
            }
            set
            {
                this.OnAnoChanging(value);
                this._Ano = value;
                this.OnAnoChanged();
                this.OnPropertyChanged("Ano");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Ano;
        partial void OnAnoChanging(string value);
        partial void OnAnoChanged();
        /// <summary>
        /// No hay comentarios para la propiedad NumFile en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string NumFile
        {
            get
            {
                return this._NumFile;
            }
            set
            {
                this.OnNumFileChanging(value);
                this._NumFile = value;
                this.OnNumFileChanged();
                this.OnPropertyChanged("NumFile");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _NumFile;
        partial void OnNumFileChanging(string value);
        partial void OnNumFileChanged();
        /// <summary>
        /// No hay comentarios para la propiedad TipTarifario en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string TipTarifario
        {
            get
            {
                return this._TipTarifario;
            }
            set
            {
                this.OnTipTarifarioChanging(value);
                this._TipTarifario = value;
                this.OnTipTarifarioChanged();
                this.OnPropertyChanged("TipTarifario");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _TipTarifario;
        partial void OnTipTarifarioChanging(string value);
        partial void OnTipTarifarioChanged();
        /// <summary>
        /// No hay comentarios para la propiedad NumFileFisico en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string NumFileFisico
        {
            get
            {
                return this._NumFileFisico;
            }
            set
            {
                this.OnNumFileFisicoChanging(value);
                this._NumFileFisico = value;
                this.OnNumFileFisicoChanged();
                this.OnPropertyChanged("NumFileFisico");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _NumFileFisico;
        partial void OnNumFileFisicoChanging(string value);
        partial void OnNumFileFisicoChanged();
        /// <summary>
        /// No hay comentarios para la propiedad AnoFile en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AnoFile
        {
            get
            {
                return this._AnoFile;
            }
            set
            {
                this.OnAnoFileChanging(value);
                this._AnoFile = value;
                this.OnAnoFileChanged();
                this.OnPropertyChanged("AnoFile");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AnoFile;
        partial void OnAnoFileChanging(string value);
        partial void OnAnoFileChanged();
        /// <summary>
        /// No hay comentarios para la propiedad Nombre en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Nombre
        {
            get
            {
                return this._Nombre;
            }
            set
            {
                this.OnNombreChanging(value);
                this._Nombre = value;
                this.OnNombreChanged();
                this.OnPropertyChanged("Nombre");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Nombre;
        partial void OnNombreChanging(string value);
        partial void OnNombreChanged();
        /// <summary>
        /// No hay comentarios para la propiedad Mercado en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Mercado
        {
            get
            {
                return this._Mercado;
            }
            set
            {
                this.OnMercadoChanging(value);
                this._Mercado = value;
                this.OnMercadoChanged();
                this.OnPropertyChanged("Mercado");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Mercado;
        partial void OnMercadoChanging(string value);
        partial void OnMercadoChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// No hay comentarios para DCModelo.Documento en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// DocumentoID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Documentoes")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("DocumentoID")]
    public partial class Documento : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Crear un nuevo objeto Documento.
        /// </summary>
        /// <param name="documentoID">Valor inicial de DocumentoID.</param>
        /// <param name="ano">Valor inicial de Ano.</param>
        /// <param name="numFile">Valor inicial de NumFile.</param>
        /// <param name="numFileFisico">Valor inicial de NumFileFisico.</param>
        /// <param name="procesoID">Valor inicial de ProcesoID.</param>
        /// <param name="tipoID">Valor inicial de TipoID.</param>
        /// <param name="nombre">Valor inicial de Nombre.</param>
        /// <param name="cuentaID">Valor inicial de CuentaID.</param>
        /// <param name="carpeta">Valor inicial de Carpeta.</param>
        /// <param name="identificador">Valor inicial de Identificador.</param>
        /// <param name="archivo">Valor inicial de Archivo.</param>
        /// <param name="fechaHora">Valor inicial de FechaHora.</param>
        /// <param name="fechaHoraProceso">Valor inicial de FechaHoraProceso.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Documento CreateDocumento(long documentoID, string ano, string numFile, string numFileFisico, short procesoID, short tipoID, string nombre, string cuentaID, string carpeta, string identificador, string archivo, global::System.DateTime fechaHora, global::System.DateTime fechaHoraProceso)
        {
            Documento documento = new Documento();
            documento.DocumentoID = documentoID;
            documento.Ano = ano;
            documento.NumFile = numFile;
            documento.NumFileFisico = numFileFisico;
            documento.ProcesoID = procesoID;
            documento.TipoID = tipoID;
            documento.Nombre = nombre;
            documento.CuentaID = cuentaID;
            documento.Carpeta = carpeta;
            documento.Identificador = identificador;
            documento.Archivo = archivo;
            documento.FechaHora = fechaHora;
            documento.FechaHoraProceso = fechaHoraProceso;
            return documento;
        }
        /// <summary>
        /// No hay comentarios para la propiedad DocumentoID en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long DocumentoID
        {
            get
            {
                return this._DocumentoID;
            }
            set
            {
                this.OnDocumentoIDChanging(value);
                this._DocumentoID = value;
                this.OnDocumentoIDChanged();
                this.OnPropertyChanged("DocumentoID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _DocumentoID;
        partial void OnDocumentoIDChanging(long value);
        partial void OnDocumentoIDChanged();
        /// <summary>
        /// No hay comentarios para la propiedad Ano en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Ano
        {
            get
            {
                return this._Ano;
            }
            set
            {
                this.OnAnoChanging(value);
                this._Ano = value;
                this.OnAnoChanged();
                this.OnPropertyChanged("Ano");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Ano;
        partial void OnAnoChanging(string value);
        partial void OnAnoChanged();
        /// <summary>
        /// No hay comentarios para la propiedad NumFile en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string NumFile
        {
            get
            {
                return this._NumFile;
            }
            set
            {
                this.OnNumFileChanging(value);
                this._NumFile = value;
                this.OnNumFileChanged();
                this.OnPropertyChanged("NumFile");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _NumFile;
        partial void OnNumFileChanging(string value);
        partial void OnNumFileChanged();
        /// <summary>
        /// No hay comentarios para la propiedad NumFileFisico en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string NumFileFisico
        {
            get
            {
                return this._NumFileFisico;
            }
            set
            {
                this.OnNumFileFisicoChanging(value);
                this._NumFileFisico = value;
                this.OnNumFileFisicoChanged();
                this.OnPropertyChanged("NumFileFisico");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _NumFileFisico;
        partial void OnNumFileFisicoChanging(string value);
        partial void OnNumFileFisicoChanged();
        /// <summary>
        /// No hay comentarios para la propiedad ProcesoID en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public short ProcesoID
        {
            get
            {
                return this._ProcesoID;
            }
            set
            {
                this.OnProcesoIDChanging(value);
                this._ProcesoID = value;
                this.OnProcesoIDChanged();
                this.OnPropertyChanged("ProcesoID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private short _ProcesoID;
        partial void OnProcesoIDChanging(short value);
        partial void OnProcesoIDChanged();
        /// <summary>
        /// No hay comentarios para la propiedad TipoID en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public short TipoID
        {
            get
            {
                return this._TipoID;
            }
            set
            {
                this.OnTipoIDChanging(value);
                this._TipoID = value;
                this.OnTipoIDChanged();
                this.OnPropertyChanged("TipoID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private short _TipoID;
        partial void OnTipoIDChanging(short value);
        partial void OnTipoIDChanged();
        /// <summary>
        /// No hay comentarios para la propiedad Nombre en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Nombre
        {
            get
            {
                return this._Nombre;
            }
            set
            {
                this.OnNombreChanging(value);
                this._Nombre = value;
                this.OnNombreChanged();
                this.OnPropertyChanged("Nombre");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Nombre;
        partial void OnNombreChanging(string value);
        partial void OnNombreChanged();
        /// <summary>
        /// No hay comentarios para la propiedad Nota en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Nota
        {
            get
            {
                return this._Nota;
            }
            set
            {
                this.OnNotaChanging(value);
                this._Nota = value;
                this.OnNotaChanged();
                this.OnPropertyChanged("Nota");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Nota;
        partial void OnNotaChanging(string value);
        partial void OnNotaChanged();
        /// <summary>
        /// No hay comentarios para la propiedad CuentaID en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CuentaID
        {
            get
            {
                return this._CuentaID;
            }
            set
            {
                this.OnCuentaIDChanging(value);
                this._CuentaID = value;
                this.OnCuentaIDChanged();
                this.OnPropertyChanged("CuentaID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CuentaID;
        partial void OnCuentaIDChanging(string value);
        partial void OnCuentaIDChanged();
        /// <summary>
        /// No hay comentarios para la propiedad Carpeta en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Carpeta
        {
            get
            {
                return this._Carpeta;
            }
            set
            {
                this.OnCarpetaChanging(value);
                this._Carpeta = value;
                this.OnCarpetaChanged();
                this.OnPropertyChanged("Carpeta");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Carpeta;
        partial void OnCarpetaChanging(string value);
        partial void OnCarpetaChanged();
        /// <summary>
        /// No hay comentarios para la propiedad Identificador en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Identificador
        {
            get
            {
                return this._Identificador;
            }
            set
            {
                this.OnIdentificadorChanging(value);
                this._Identificador = value;
                this.OnIdentificadorChanged();
                this.OnPropertyChanged("Identificador");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Identificador;
        partial void OnIdentificadorChanging(string value);
        partial void OnIdentificadorChanged();
        /// <summary>
        /// No hay comentarios para la propiedad Archivo en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Archivo
        {
            get
            {
                return this._Archivo;
            }
            set
            {
                this.OnArchivoChanging(value);
                this._Archivo = value;
                this.OnArchivoChanged();
                this.OnPropertyChanged("Archivo");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Archivo;
        partial void OnArchivoChanging(string value);
        partial void OnArchivoChanged();
        /// <summary>
        /// No hay comentarios para la propiedad Sender en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Sender
        {
            get
            {
                return this._Sender;
            }
            set
            {
                this.OnSenderChanging(value);
                this._Sender = value;
                this.OnSenderChanged();
                this.OnPropertyChanged("Sender");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Sender;
        partial void OnSenderChanging(string value);
        partial void OnSenderChanged();
        /// <summary>
        /// No hay comentarios para la propiedad Reciever en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Reciever
        {
            get
            {
                return this._Reciever;
            }
            set
            {
                this.OnRecieverChanging(value);
                this._Reciever = value;
                this.OnRecieverChanged();
                this.OnPropertyChanged("Reciever");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Reciever;
        partial void OnRecieverChanging(string value);
        partial void OnRecieverChanged();
        /// <summary>
        /// No hay comentarios para la propiedad FechaHora en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime FechaHora
        {
            get
            {
                return this._FechaHora;
            }
            set
            {
                this.OnFechaHoraChanging(value);
                this._FechaHora = value;
                this.OnFechaHoraChanged();
                this.OnPropertyChanged("FechaHora");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _FechaHora;
        partial void OnFechaHoraChanging(global::System.DateTime value);
        partial void OnFechaHoraChanged();
        /// <summary>
        /// No hay comentarios para la propiedad FechaHoraProceso en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime FechaHoraProceso
        {
            get
            {
                return this._FechaHoraProceso;
            }
            set
            {
                this.OnFechaHoraProcesoChanging(value);
                this._FechaHoraProceso = value;
                this.OnFechaHoraProcesoChanged();
                this.OnPropertyChanged("FechaHoraProceso");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _FechaHoraProceso;
        partial void OnFechaHoraProcesoChanging(global::System.DateTime value);
        partial void OnFechaHoraProcesoChanged();
        /// <summary>
        /// No hay comentarios para Cuenta en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Cuenta Cuenta
        {
            get
            {
                return this._Cuenta;
            }
            set
            {
                this._Cuenta = value;
                this.OnPropertyChanged("Cuenta");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Cuenta _Cuenta;
        /// <summary>
        /// No hay comentarios para Proceso en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Proceso Proceso
        {
            get
            {
                return this._Proceso;
            }
            set
            {
                this._Proceso = value;
                this.OnPropertyChanged("Proceso");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Proceso _Proceso;
        /// <summary>
        /// No hay comentarios para Tipo en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Tipo Tipo
        {
            get
            {
                return this._Tipo;
            }
            set
            {
                this._Tipo = value;
                this.OnPropertyChanged("Tipo");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Tipo _Tipo;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
