//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCAddIn.DCServicio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FilePrincipal", Namespace="http://schemas.datacontract.org/2004/07/DCServicio")]
    [System.SerializableAttribute()]
    public partial class FilePrincipal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnoFileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MercadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumFileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumFileFisicoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ano {
            get {
                return this.AnoField;
            }
            set {
                if ((object.ReferenceEquals(this.AnoField, value) != true)) {
                    this.AnoField = value;
                    this.RaisePropertyChanged("Ano");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnoFile {
            get {
                return this.AnoFileField;
            }
            set {
                if ((object.ReferenceEquals(this.AnoFileField, value) != true)) {
                    this.AnoFileField = value;
                    this.RaisePropertyChanged("AnoFile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mercado {
            get {
                return this.MercadoField;
            }
            set {
                if ((object.ReferenceEquals(this.MercadoField, value) != true)) {
                    this.MercadoField = value;
                    this.RaisePropertyChanged("Mercado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumFile {
            get {
                return this.NumFileField;
            }
            set {
                if ((object.ReferenceEquals(this.NumFileField, value) != true)) {
                    this.NumFileField = value;
                    this.RaisePropertyChanged("NumFile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumFileFisico {
            get {
                return this.NumFileFisicoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumFileFisicoField, value) != true)) {
                    this.NumFileFisicoField = value;
                    this.RaisePropertyChanged("NumFileFisico");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tipo", Namespace="http://schemas.datacontract.org/2004/07/DCServicio")]
    [System.SerializableAttribute()]
    public partial class Tipo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoID {
            get {
                return this.TipoIDField;
            }
            set {
                if ((this.TipoIDField.Equals(value) != true)) {
                    this.TipoIDField = value;
                    this.RaisePropertyChanged("TipoID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Proceso", Namespace="http://schemas.datacontract.org/2004/07/DCServicio")]
    [System.SerializableAttribute()]
    public partial class Proceso : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProcesoIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProcesoID {
            get {
                return this.ProcesoIDField;
            }
            set {
                if ((this.ProcesoIDField.Equals(value) != true)) {
                    this.ProcesoIDField = value;
                    this.RaisePropertyChanged("ProcesoID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DCArchivo", Namespace="http://schemas.datacontract.org/2004/07/DCServicio")]
    [System.SerializableAttribute()]
    public partial class DCArchivo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArchivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaHoraProcesoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Archivo {
            get {
                return this.ArchivoField;
            }
            set {
                if ((object.ReferenceEquals(this.ArchivoField, value) != true)) {
                    this.ArchivoField = value;
                    this.RaisePropertyChanged("Archivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaHoraProceso {
            get {
                return this.FechaHoraProcesoField;
            }
            set {
                if ((this.FechaHoraProcesoField.Equals(value) != true)) {
                    this.FechaHoraProcesoField = value;
                    this.RaisePropertyChanged("FechaHoraProceso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DCServicio.IDCServicio")]
    public interface IDCServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDCServicio/GetFilePrincipalByAnoFile", ReplyAction="http://tempuri.org/IDCServicio/GetFilePrincipalByAnoFileResponse")]
        DCAddIn.DCServicio.FilePrincipal GetFilePrincipalByAnoFile(string anoFile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDCServicio/GetFilePrincipalByAnoFile", ReplyAction="http://tempuri.org/IDCServicio/GetFilePrincipalByAnoFileResponse")]
        System.Threading.Tasks.Task<DCAddIn.DCServicio.FilePrincipal> GetFilePrincipalByAnoFileAsync(string anoFile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDCServicio/GetTipos", ReplyAction="http://tempuri.org/IDCServicio/GetTiposResponse")]
        System.Collections.Generic.List<DCAddIn.DCServicio.Tipo> GetTipos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDCServicio/GetTipos", ReplyAction="http://tempuri.org/IDCServicio/GetTiposResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DCAddIn.DCServicio.Tipo>> GetTiposAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDCServicio/GetProcesos", ReplyAction="http://tempuri.org/IDCServicio/GetProcesosResponse")]
        System.Collections.Generic.List<DCAddIn.DCServicio.Proceso> GetProcesos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDCServicio/GetProcesos", ReplyAction="http://tempuri.org/IDCServicio/GetProcesosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DCAddIn.DCServicio.Proceso>> GetProcesosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDCServicio/ProcesarCorreos", ReplyAction="http://tempuri.org/IDCServicio/ProcesarCorreosResponse")]
        System.Collections.Generic.List<int> ProcesarCorreos(System.Collections.Generic.List<System.Data.DataTable> tablas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDCServicio/ProcesarCorreos", ReplyAction="http://tempuri.org/IDCServicio/ProcesarCorreosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<int>> ProcesarCorreosAsync(System.Collections.Generic.List<System.Data.DataTable> tablas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDCServicio/ProcesarArchivos", ReplyAction="http://tempuri.org/IDCServicio/ProcesarArchivosResponse")]
        System.Collections.Generic.List<int> ProcesarArchivos(System.Data.DataTable tabla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDCServicio/ProcesarArchivos", ReplyAction="http://tempuri.org/IDCServicio/ProcesarArchivosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<int>> ProcesarArchivosAsync(System.Data.DataTable tabla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDCServicio/BorrarDocumento", ReplyAction="http://tempuri.org/IDCServicio/BorrarDocumentoResponse")]
        bool BorrarDocumento(int documentoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDCServicio/BorrarDocumento", ReplyAction="http://tempuri.org/IDCServicio/BorrarDocumentoResponse")]
        System.Threading.Tasks.Task<bool> BorrarDocumentoAsync(int documentoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDCServicio/EditarDocumento", ReplyAction="http://tempuri.org/IDCServicio/EditarDocumentoResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<System.Data.DataTable>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<int>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DCAddIn.DCServicio.FilePrincipal))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<DCAddIn.DCServicio.Tipo>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DCAddIn.DCServicio.Tipo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<DCAddIn.DCServicio.Proceso>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DCAddIn.DCServicio.Proceso))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DCAddIn.DCServicio.DCArchivo))]
        bool EditarDocumento(int documentoID, System.Collections.Generic.List<object> datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDCServicio/EditarDocumento", ReplyAction="http://tempuri.org/IDCServicio/EditarDocumentoResponse")]
        System.Threading.Tasks.Task<bool> EditarDocumentoAsync(int documentoID, System.Collections.Generic.List<object> datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDCServicio/DescargarDCArchivo", ReplyAction="http://tempuri.org/IDCServicio/DescargarDCArchivoResponse")]
        DCAddIn.DCServicio.DCArchivo DescargarDCArchivo(int documentoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDCServicio/DescargarDCArchivo", ReplyAction="http://tempuri.org/IDCServicio/DescargarDCArchivoResponse")]
        System.Threading.Tasks.Task<DCAddIn.DCServicio.DCArchivo> DescargarDCArchivoAsync(int documentoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDCServicio/EsAdministrador", ReplyAction="http://tempuri.org/IDCServicio/EsAdministradorResponse")]
        bool EsAdministrador(string cuentaID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDCServicio/EsAdministrador", ReplyAction="http://tempuri.org/IDCServicio/EsAdministradorResponse")]
        System.Threading.Tasks.Task<bool> EsAdministradorAsync(string cuentaID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDCServicioChannel : DCAddIn.DCServicio.IDCServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DCServicioClient : System.ServiceModel.ClientBase<DCAddIn.DCServicio.IDCServicio>, DCAddIn.DCServicio.IDCServicio {
        
        public DCServicioClient() {
        }
        
        public DCServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DCServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DCServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DCServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DCAddIn.DCServicio.FilePrincipal GetFilePrincipalByAnoFile(string anoFile) {
            return base.Channel.GetFilePrincipalByAnoFile(anoFile);
        }
        
        public System.Threading.Tasks.Task<DCAddIn.DCServicio.FilePrincipal> GetFilePrincipalByAnoFileAsync(string anoFile) {
            return base.Channel.GetFilePrincipalByAnoFileAsync(anoFile);
        }
        
        public System.Collections.Generic.List<DCAddIn.DCServicio.Tipo> GetTipos() {
            return base.Channel.GetTipos();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DCAddIn.DCServicio.Tipo>> GetTiposAsync() {
            return base.Channel.GetTiposAsync();
        }
        
        public System.Collections.Generic.List<DCAddIn.DCServicio.Proceso> GetProcesos() {
            return base.Channel.GetProcesos();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DCAddIn.DCServicio.Proceso>> GetProcesosAsync() {
            return base.Channel.GetProcesosAsync();
        }
        
        public System.Collections.Generic.List<int> ProcesarCorreos(System.Collections.Generic.List<System.Data.DataTable> tablas) {
            return base.Channel.ProcesarCorreos(tablas);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<int>> ProcesarCorreosAsync(System.Collections.Generic.List<System.Data.DataTable> tablas) {
            return base.Channel.ProcesarCorreosAsync(tablas);
        }
        
        public System.Collections.Generic.List<int> ProcesarArchivos(System.Data.DataTable tabla) {
            return base.Channel.ProcesarArchivos(tabla);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<int>> ProcesarArchivosAsync(System.Data.DataTable tabla) {
            return base.Channel.ProcesarArchivosAsync(tabla);
        }
        
        public bool BorrarDocumento(int documentoID) {
            return base.Channel.BorrarDocumento(documentoID);
        }
        
        public System.Threading.Tasks.Task<bool> BorrarDocumentoAsync(int documentoID) {
            return base.Channel.BorrarDocumentoAsync(documentoID);
        }
        
        public bool EditarDocumento(int documentoID, System.Collections.Generic.List<object> datos) {
            return base.Channel.EditarDocumento(documentoID, datos);
        }
        
        public System.Threading.Tasks.Task<bool> EditarDocumentoAsync(int documentoID, System.Collections.Generic.List<object> datos) {
            return base.Channel.EditarDocumentoAsync(documentoID, datos);
        }
        
        public DCAddIn.DCServicio.DCArchivo DescargarDCArchivo(int documentoID) {
            return base.Channel.DescargarDCArchivo(documentoID);
        }
        
        public System.Threading.Tasks.Task<DCAddIn.DCServicio.DCArchivo> DescargarDCArchivoAsync(int documentoID) {
            return base.Channel.DescargarDCArchivoAsync(documentoID);
        }
        
        public bool EsAdministrador(string cuentaID) {
            return base.Channel.EsAdministrador(cuentaID);
        }
        
        public System.Threading.Tasks.Task<bool> EsAdministradorAsync(string cuentaID) {
            return base.Channel.EsAdministradorAsync(cuentaID);
        }
    }
}
