//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCModelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Tipo> Tipoes { get; set; }
        public DbSet<Proceso> Procesoes { get; set; }
        public DbSet<Cuenta> Cuentas { get; set; }
        public DbSet<DocumentoFile> DocumentoFiles { get; set; }
        public DbSet<FilePrincipal> FilePrincipals { get; set; }
        public DbSet<Documento> Documentoes { get; set; }
    }
}
