//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentoFile
    {
        public long DocumentoID { get; set; }
        public string Ano { get; set; }
        public string NumFile { get; set; }
        public string NumFileFisico { get; set; }
        public short ProcesoID { get; set; }
        public short TipoID { get; set; }
        public string Nombre { get; set; }
        public string Nota { get; set; }
        public string CuentaID { get; set; }
        public string Carpeta { get; set; }
        public string Identificador { get; set; }
        public string Archivo { get; set; }
        public string Sender { get; set; }
        public string Reciever { get; set; }
        public System.DateTime FechaHora { get; set; }
        public System.DateTime FechaHoraProceso { get; set; }
        public string NombreFile { get; set; }
        public string Mercado { get; set; }
        public string NombreCliente { get; set; }
        public string CodigoCliente { get; set; }
        public string AnoFile { get; set; }
    }
}
