//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCModelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilePrincipal
    {
        public string Ano { get; set; }
        public string NumFile { get; set; }
        public string TipTarifario { get; set; }
        public string NumFileFisico { get; set; }
        public string AnoFile { get; set; }
        public string Nombre { get; set; }
        public string Mercado { get; set; }
    }
}
